name: Backend Image CI
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build backend
              run: docker build ../backend --file ../backend Dockerfile --tag backend-dream-vacs:$(date+%s)

    